/*
 * This source file was generated by the Gradle 'init' task
 */
package org.yourcompany.yourproject;

public class App {
    public static void main(String[] args) {
        org.yourcompany.yourproject.Jfx.main(args);
    }
}
